### ISSUE TITLE
User role

### ISSUE THREAD

**Issue by ruehsflo** [ronnyporsch/webapps7client#1]
Is it possible for a user to have both roles?

And since it is splitted up into two tasks: should the role be assigned when a user is created or can this happen later?

**Comment by ronnyporsch** [comment]
the roles should be considered mutually exclusive. They can be added during creation of a user but it should be possible to change them later as well

**Comment by ruehsflo** [comment]
So it is not intended that a user can be for example a teacher for one class and a student for another one?

**Comment by ronnyporsch** [comment]
yes that is correct
