### ISSUE TITLE
Domain information Model

### ISSUE THREAD

**Issue by ruehsflo** [ronnyporsch/webapps7client#5]
We created a domain information model corresponding to your current description. Is this what you had in mind?

**Comment by ronnyporsch** [comment]
the structure looks very good but to my understanding there should also be attributes in this model

**Comment by ruehsflo** [comment]
Therer should be a complete inheritance of user right?

**Comment by ruehsflo** [comment]
Hey I updated the domain information model, can you tell me if its alright?

**Comment by ronnyporsch** [comment]
looks pretty good! Just two very small things:
- level should only be an attribute in class, not in event
- the inheritance from event is not only complete but also disjoint

other than that i'm very pleased :)
