### ISSUE TITLE
Design Information Model

### ISSUE THREAD

**Issue by PramitKumar27** [ronnyporsch/webapps7client#6]
Kindly check the diagram and revert if any changes are to be made. :)

**Comment by ronnyporsch** [comment]
- the role can be a simple enum with no additional attributes.
-  in the domain information model, student and teacher were extending a common superclass. That seemed like a pretty good idea. Why is that not the case anymore?
- style is an attribute of events. It is not for students/teachers
- level should not be optional in the event. Also, an invariant is needed which states that the range is 1-5
